### ISSUE TITLE
Review notes

### ISSUE THREAD

**Issue by chrisvfritz** [howell33/authenication#1]
It looks like there's one criterion that you forgot:

> NOT display any links to unauthorized actions to anonymous visitors (such as links to create a new record, edit a record, or delete a record)

Check out how we're only showing a link to sign out if a user is signed in and use the same technique to only show links to these actions when signed in.

**Comment by howell33** [comment]
updated

**Comment by chrisvfritz** [comment]
Almost perfect now. The only thing missing is that you went _a little_ too far and are now also hiding [the link to the Show page here](https://github.com/howell33/authenication/blob/0b25fdd84157aa0cfa0a4d24240789eced43f071/app/views/dance_teams/index.html.erb#L30) for anonymous users, when they should still be able to see it.

**Comment by howell33** [comment]
updated

**Comment by chrisvfritz** [comment]
:+1: Nice!
